<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Scripts</AssemblyName>
    <RootNamespace>Puzzle</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../engine/managed/Dunya.Engine/Dunya.Engine.csproj" Private="false" />
  </ItemGroup>

</Project>
