#version 450
#extension GL_GOOGLE_include_directive : require

#include "sdf-types.glsl"

const int MAX_SDF_VOLUMES = DUNYA_MAX_SDF_VOLUMES;

layout(std430, set = 0, binding = 3) readonly buffer FieldScene {
  Primitive primitives[];
} scene;

layout(r32f,
       set = 0,
       binding = 4) uniform writeonly image3D distanceVolume[MAX_SDF_VOLUMES];
layout(r8ui,
       set = 0,
       binding = 5)
  uniform writeonly uimage3D materialVolume[MAX_SDF_VOLUMES];

layout(push_constant) uniform BakeParams {
  vec4 origin;
  vec4 voxelSize;
  uvec4 resolution;
  uvec4 volume;
} params;

#define FIELD_PRIMITIVE_AT(i) scene.primitives[params.volume.y + (i)]

#define FIELD_PRIMITIVE_COUNT params.resolution.w

#include "sdf-common.glsl"

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

void main() {
  uvec3 at = gl_GlobalInvocationID;

  if (any(greaterThanEqual(at, params.resolution.xyz))) {
    return;
  }

  vec3 p = params.origin.xyz + params.voxelSize.xyz * vec3(at);

  vec2 field = sceneDistance(p);

  uint volume = params.volume.x;

  imageStore(distanceVolume[volume], ivec3(at), vec4(field.x, 0.0, 0.0, 0.0));
  imageStore(materialVolume[volume],
             ivec3(at),
             uvec4(uint(field.y + 0.5), 0u, 0u, 0u));
}
